### ISSUE TITLE
Just a few thoughts

### ISSUE THREAD

**Issue by ebioman** [rrwick/Filtlong#1]
Hi, an interesting project.
I am curious, for the reference based approach: did you have a look at low complexity, repeat-rich regions or abnormal GC-rich regions?
As with other applications using Illumina for polishing or evaluation I fear that the main advantage of long reads - to span across these regions - might be lost using such a method.
Cheers

**Comment by rrwick** [comment]
No, I haven't specifically examined whether Filtlong introduces biases to any particular kind of sequences. If you find that is does, please share your results!

In general, I suspect that using Illumina reads as a reference would be safer than using an assembly as a reference. Consider low-complexity, repeat-rich regions. Those regions should be well represented in Illumina reads, so Filtlong should find their k-mers just fine. But if those regions assembled poorly and were excluded from the contigs, then the k-mers might be absent.

I'm not sure about GC-rich regions. I suppose if these are very underrepresented in the Illumina reads, then it could be a problem. But again, I'd expect Illumina reads to be a safer reference than an assembly. If the GC rich region had at least _some_ Illumina coverage, then it should be okay.

Ryan

**Comment by rrwick** [comment]
I'll close this issue now, as I don't have anything in particular to change with Filtlong. But feel free to reopen it if you have new info or encounter a specific problem. Thanks!
