### ISSUE TITLE
maximum read length

### ISSUE THREAD

**Issue by sarah872** [rrwick/Filtlong#12]
Is there a way to restrict the read dataset to a maximum read length? I try to assemble a 8kbp plasmid sequenced with a 2.4Mbp bacterial genome.

**Comment by rrwick** [comment]
I'm afraid I didn't add a `--max_length` option to Filtlong, as usually the long reads are what we want! 

I'd suggest filtering out too-long reads first (some ideas here: https://www.biostars.org/p/62678/) and then running Filtlong if you still have an excessive volume of reads.

Ryan
