### ISSUE TITLE
--min_mean_q not working

### ISSUE THREAD

**Issue by dcopetti** [rrwick/Filtlong#18]
Hello,
I am trying to remove low quality reads from a fastq file of PromethION data, but the command
`filtlong --min_length 2000 --min_mean_q 7 input.fq >ouput.fq`
still has the bad reads in it:
![Capture](https://user-images.githubusercontent.com/13842014/62680536-b9456f80-b9b7-11e9-804c-f0934778d809.JPG)
This is how the input looks like:
```
$ head -n 20 input.fq |  cut -c1-200
@09b90259-4c4b-45a6-a25f-bb379532131e runid=52d261662a02ed5e268a75306cda2f80d2269b4e sampleid=Lolium_2 read=42864 ch=1675 start_time=2018-10-18T09:47:00Z
GTTGTACTTCGTTTACGTTCAGTTACAGCGTACTTGGCGTCCTTGTCTTCCTCTTTCTGCCCAAGATCTCAGATCATCTTCATCAGGGAAACTCCTTGCCACATACATTCTTGGAGACCATGGGCGCTTCACAAAACTGAGAAACAGATCCCAGCAAGCATTTGCCAGCTCATTTCCTGCGATCGAGCCACGATCTGGAC
+
#&'((*,//./..&"%'211).+.%$%(#%%%%&&%+099/;561<4*5).1(44430*00.-//0&-)$&$(0-0;;<34,*')++,%(&60&0''$$#%)')&)*-0-86640.5-*)'&'0)+%%,$$%340.550-'%'.,&,2%%/&$)%$')++-/.#$'0.63*''')$**)$&$$%'(&$+'.-.&%$%266
@223d04a0-c191-4321-983f-a352a7a82696 runid=52d261662a02ed5e268a75306cda2f80d2269b4e sampleid=Lolium_2 read=30812 ch=2540 start_time=2018-10-18T09:45:19Z
CATTGTACTTCGTTCAACACTTGGTTATCATACATGGATCCCATTTGGATTTCATGGCTTCTTGCCATTTGTTGGAATCTGGGCTCATCATCAGCTTCTTCATACGTCGCGAGAGTGCTTCATTATTGTTGTCCACAATCATGACATTTAGACAGGGATCATACCAATCGAGTGAGTAAAGCTCCGTCGATCTGAGGTTG
+
#%$%$&'%''&(&&%%&$&%%&''*72/;,<66<:=8C89>@<;;+)*+<>>;3::>66C:EA=64:76926643,*$(-./>871*142%'$-678:@@6-&&&(26120-%+3:68?@=>;<'))3>><=8?CAC>7?5D@?>@BB?*,*++.525*>:?>@?3446.&(*&$&+-/-.99&-)'.-3$$)%'0/-2*
@3fdc7cb0-9713-4b60-a2a4-f207ea09f08e runid=52d261662a02ed5e268a75306cda2f80d2269b4e sampleid=Lolium_2 read=30248 ch=2310 start_time=2018-10-18T09:48:20Z
ACATGCGCCAGCTCCCCAGGAGCCGAAGTGCCCGAGGATTCGCCGCGTGCGATAAGTTGAAAGAAAGAGGAAGTGGTGTCTCCGCTCCCGGCGGCCAACTATTGCGACATGGAGACCGAATTGCTAATTGCAGCGAGAATTTTGGAGTCGATGAAAAGTTGGTGGCTTTGTTGTGCAATATATGAACTGTTCTCCTCACC
+
221.&&'&&&%$')***)&&%+&&(')&+&***%%3.3697+*)%&%11242%*/4154-,-+-,41'%&)*-)&*9+;95$)*.6';.-.((/22.../-.047554/.(-)'1*4)$$$&,68-8--))$%%&('))&----.%--079459=?<=53,'4'823;?;456=7>>=53+)%%%,)'(**()&.-#$%%
@52f5daa6-4253-47b7-8c9f-76bfeea60fe9 runid=52d261662a02ed5e268a75306cda2f80d2269b4e sampleid=Lolium_2 read=38570 ch=2601 start_time=2018-10-18T09:49:06Z
CAGTATGGGTATCTAGAATTCCCGAGAGGACTGCTCTAGGTGACTTGTATTTTGAAGGGGTGACCAGAGAGGGAGTGGCATGATGGTATCATGCCGTAGTCGGCCTTAGAAGCTTTTGAGTGAGAAGGTGAGCGAGGCTCCCGGTGTTTACGGGGTGATGGAAATGGTTGCGGAGGTGAGGTGATGCTCGAGGCTGCGAG
+
%$'$$%$&)%$)%#*%&$$%$-2,+)+'.227,"$%$%%'10/&'''()**)(((($%%%$**)*+%)).-&-&(++/-,%+#,'-$$,*)(-)(('&&&'$*))&&$&$$((6620*'2)('&113768,*03+(,0()7*')5)23.%#$%++''+,,,)*%&%%*&)2%,*5310'8>:?;:?>/.&$1.01%&+%3
@5f1659ec-c649-4fbb-98c3-c8b048a213bd runid=52d261662a02ed5e268a75306cda2f80d2269b4e sampleid=Lolium_2 read=38158 ch=2075 start_time=2018-10-18T09:46:24Z
CGATTGCCCACTTCGTTCAGTTATTACTCTACGCTTACCACCAGATCACTTTATTATAACCTGCAGAATTACAGGATGAATTCTGAGATAAAACACAAGTACAGTCTCACTGTTGCTGATACCCCATCAACATGGGAATAGTTTTTCAAAATCTCAGAAAATGCGAGAGCTCAGAAATTTGACAGTTGCATTTGGACTTA
+
#$$$%%$&&%)+,)+11.+0+-$%*,400*,&%%%($%&&$'$%&'('######$#)%%#%$#%%$&$$&((*+($&###$(&$$$&$%'(($#%$')#('*$#%*$%)'&$%%%%&%%'&+*($,-400/-%,,+&&&'+&332,(%&&'*/%'#$$%%%%%"%%%%$2/0&$')%%(*-($%,/)$#%#(*$**+3+0
```
is there some problem in the header maybe? I did not manipulate the file though.
I did this twice on two files and double checked the command for typos, but the low quality reads are still there. With other files from another run on the same instrument, the selection works fine.
Any guess?

**Comment by kapsakcj** [comment]
I believe the `--min_mean_q` flag does not use Phred q scores. Filtlong calculates its own q score value, 0-100 scale. See https://github.com/rrwick/Filtlong#read-scoring

I'd recommend running the helper script `scripts/read_info_histograms.sh` on your reads to get an idea of what the scores are, and decide on a cutoff value. Depending on the reads it may be somewhere up in the 70s, 80s, 90s. YMMV

**Comment by dcopetti** [comment]
Hi,
I was able to select the reads with the appropriate quality score, but reading your documentation I don't think that I was in the case where the score is based on a 0-100 scale, since my input was a fastq file and no reference assembly was provided.

> If there is no reference, the mean quality is the mean read identity as indicated by the Phred quality scores. For example, consider a read where all the fastq quality characters are +. The qscores for each base are 10 which equates to a 90% chance of being correct. This read would then have a mean quality score of 90.

it looks fine for me now, the 1.3 Mb read was discarded because of too low quality - now we work with reads up to 400 kb :-)
