### ISSUE TITLE
makefile failing?

### ISSUE THREAD

**Issue by nataliering** [rrwick/Filtlong#2]
Hi Ryan

Looking forward to trying this out on my most recent nanopore runs! Trying to install, but the makefile is failing for me, and I'm not sure why...here's the output:

`ubuntu@nat:~/software/Filtlong-master$ make  -j
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -mtune=native -c -o src/misc.o src/mis                                                                                       c.cpp
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -mtune=native -c -o src/arguments.o sr                                                                                       c/arguments.cpp
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -mtune=native -c -o src/kmers.o src/km                                                                                       ers.cpp
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -mtune=native -c -o src/read.o src/rea                                                                                       d.cpp
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -mtune=native -c -o src/main.o src/mai                                                                                       n.cpp
g++ -std=c++11 -O3 -Wall -Wextra -pedantic -mtune=native -lz -o bin/filtlong src/                                                                                       misc.o src/arguments.o src/kmers.o src/read.o src/main.o
src/kmers.o: In function `ks_getuntil2(__kstream_t*, int, __kstring_t*, int*, int                                                                                       ) [clone .constprop.146]':
kmers.cpp:(.text+0x63): undefined reference to `gzread'
src/kmers.o: In function `kseq_read(kseq_t*)':
kmers.cpp:(.text+0x32d): undefined reference to `gzread'
kmers.cpp:(.text+0x4c8): undefined reference to `gzread'
kmers.cpp:(.text+0x505): undefined reference to `gzread'
kmers.cpp:(.text+0x724): undefined reference to `gzread'
src/kmers.o:kmers.cpp:(.text+0x8e9): more undefined references to `gzread' follow
src/kmers.o: In function `Kmers::add_read_fastqs(std::vector<std::__cxx11::basic_                                                                                       string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::                                                                                       __cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >)':
kmers.cpp:(.text+0xd83): undefined reference to `gzopen'
kmers.cpp:(.text+0x17eb): undefined reference to `gzclose'
src/kmers.o: In function `Kmers::add_assembly_fasta(std::__cxx11::basic_string<ch                                                                                       ar, std::char_traits<char>, std::allocator<char> >)':
kmers.cpp:(.text+0x1b38): undefined reference to `gzopen'
kmers.cpp:(.text+0x256b): undefined reference to `gzclose'
src/kmers.o: In function `Kmers::add_reference(std::__cxx11::basic_string<char, s                                                                                       td::char_traits<char>, std::allocator<char> >, bool)':
kmers.cpp:(.text+0x297b): undefined reference to `gzopen'
kmers.cpp:(.text+0x33f3): undefined reference to `gzclose'
src/main.o: In function `ks_getuntil2(__kstream_t*, int, __kstring_t*, int*, int)                                                                                        [clone .constprop.117]':
main.cpp:(.text+0x4f3): undefined reference to `gzread'
src/main.o: In function `kseq_read(kseq_t*)':
main.cpp:(.text+0x7bd): undefined reference to `gzread'
main.cpp:(.text+0x958): undefined reference to `gzread'
main.cpp:(.text+0x995): undefined reference to `gzread'
main.cpp:(.text+0xbb4): undefined reference to `gzread'
src/main.o:main.cpp:(.text+0xd79): more undefined references to `gzread' follow
src/main.o: In function `main':
main.cpp:(.text.startup+0x125): undefined reference to `gzopen'
main.cpp:(.text.startup+0x76a): undefined reference to `gzclose'
main.cpp:(.text.startup+0xd34): undefined reference to `gzopen'
main.cpp:(.text.startup+0x18a2): undefined reference to `gzclose'
collect2: error: ld returned 1 exit status
Makefile:39: recipe for target 'bin/filtlong' failed
make: *** [bin/filtlong] Error 1
`

Any ideas please? Is it something I can fix from my end/work around?

Thanks a lot!
Nat

**Comment by rrwick** [comment]
I'm not sure, but this may relate to the order of flags in the Makefile. Something similar came up here: https://github.com/rrwick/Unicycler/issues/18 which was fixed like this: https://github.com/rrwick/Unicycler/commit/d8884bd74ef7e5315a58c84f29ace115bb5dc905

I made the same change in Filtlong and just pushed it to Github: c832e2846266150c9b7bf900b9efad8332634b43 Can you pull from Github and try to make it again?

If that doesn't work, then I wonder if your system is lacking the zlib library. Perhaps something like `sudo apt-get install zlib1g-dev` would get it working?

Thanks for the report and let me know how you go!

Ryan

**Comment by nataliering** [comment]
Changing the make flags seems to have worked - thanks a lot for your speedy fix!

**Comment by rrwick** [comment]
Glad to hear it!
