### ISSUE TITLE
citation 

### ISSUE THREAD

**Issue by BioRB** [rrwick/Filtlong#21]
Hello,
How can we cite Filtlong in a publication?
thanks.

**Comment by matryoskina** [comment]
Hi!
I have the same question. Someone knows the answer?
Thanks

**Comment by PanZiwei** [comment]
Waiting for the response! It would be very beneficial if the author can provide an example citation format.

**Comment by rrwick** [comment]
Sorry, but I never did bother making a manuscript for this one. Filtlong's gotten a fair bit of use, so in hindsight I probably should have! But it's too late now 🤷 

So I'm afraid that this GitHub page is the only thing to cite!
