### ISSUE TITLE
read_info_histograms.sh   not working

### ISSUE THREAD

**Issue by limin321** [rrwick/Filtlong#23]
Hi, to whom it may concern,

I am a newer to data analysis, know little about command lines. I try to look at my long sequence data quality with filtlong, here is what I did as following.

I have downloaded both histogram.py  and read_info_histograms.sh in my working folder, 
nanopor_QC$ ls 
histogram.py  read_info_histograms.sh

nanopor_QC$ read_info_histograms.sh ../ln_Kin002_long.fastq 
-bash: read_info_histograms.sh: command not found

However,  it says command not found.  Can anyone help me what is going on with this issue? 
Your helps are greatly appreciated.

**Comment by tolot27** [comment]
You have to prepend the current path if the executable just not in the global path. Try `./read_info_histograms.sh ../ln_Kin002_long.fastq`

**Comment by limin321** [comment]
> ./read_info_histograms.sh ../ln_Kin002_long.fastq

Thanks  ! tolot27.  I tried again, but it has some other issues.
<img width="1007" alt="Screen Shot 2019-12-30 at 2 57 16 PM" src="https://user-images.githubusercontent.com/42760669/71604102-edf7c600-2b14-11ea-96e2-860695d68c4e.png">


<img width="1282" alt="Screen Shot 2019-12-30 at 2 57 48 PM" src="https://user-images.githubusercontent.com/42760669/71604106-f223e380-2b14-11ea-91a3-9e06af6bf885.png">

I pasted the screen shot of the issue here.  could you please help me troubleshooting again?  Thanks a lot. I don't see what the real issue it maybe.
Best,

**Comment by tolot27** [comment]
@limin321 You did not download the real script files; instead, you downloaded the html representation. Please follow the file links and right-click on raw to save the script files.
![image](https://user-images.githubusercontent.com/1370732/71623176-f9152980-2bda-11ea-8e9c-732a1f8fa1c7.png)

**Comment by limin321** [comment]
> @limin321 You did not download the real script files; instead, you downloaded the html representation. Please follow the file links and right-click on raw to save the script files.
> ![image](https://user-images.githubusercontent.com/1370732/71623176-f9152980-2bda-11ea-8e9c-732a1f8fa1c7.png)

Hi Thank you so much.  I downloaded according to your methods.  However I still ran into some issues.  here is the problem, could you please help me do the trouble shooting again?

<img width="1077" alt="Screen Shot 2020-01-07 at 1 45 50 PM" src="https://user-images.githubusercontent.com/42760669/71932076-06d72b80-3154-11ea-8e7d-734c27dfdba1.png">


What might be the issue???    
really appreciate all your help.

**Comment by tolot27** [comment]
You need to download/clone the complete filtlong project, because `read_info_histograms.sh` depends on the `filtlong` executable.
After cloning the project, go to your data directory (`/share/amishalab-backedup/Kluepfel/limchen/MiSeq_Data/Kin002`) and call `<root path of filtlong>/filtlong/scripts/read_info_histograms.sh ln_Kin002_long.fastq`.

**Comment by limin321** [comment]
> You need to download/clone the complete filtlong project, because `read_info_histograms.sh` depends on the `filtlong` executable.
> After cloning the project, go to your data directory (`/share/amishalab-backedup/Kluepfel/limchen/MiSeq_Data/Kin002`) and call `<root path of filtlong>/filtlong/scripts/read_info_histograms.sh ln_Kin002_long.fastq`.


Hi,  tolot27! 

Thank you so much!  Thank you so much.  It works now. I pasted my results to share.  I  am really appreciate your help. You are amazing.   

Best regards,

<img width="496" alt="Screen Shot 2020-01-15 at 4 54 48 PM" src="https://user-images.githubusercontent.com/42760669/72484004-c01eac80-37b7-11ea-8df8-e6ca08d1a225.png">

**Comment by limin321** [comment]
> You need to download/clone the complete filtlong project, because `read_info_histograms.sh` depends on the `filtlong` executable.
> After cloning the project, go to your data directory (`/share/amishalab-backedup/Kluepfel/limchen/MiSeq_Data/Kin002`) and call `<root path of filtlong>/filtlong/scripts/read_info_histograms.sh ln_Kin002_long.fastq`.

Hi Tolot27,

As the output I showed above, do you have any idea why the MEAN QUALITIES only the same values? I feel like it is not correct.  what should I do to correct it?

Best ,

**Comment by tolot27** [comment]
@limin321 That's a different problem I've also observed. Please open a separate issue for it.

Afterwards, please close this issue if it is solved completely.

**Comment by limin321** [comment]
Thanks a lot. @tolot27   I am going to open a new issue.
