### ISSUE TITLE
Something wrong with filtered fastq file

### ISSUE THREAD

**Issue by nataliering** [rrwick/Filtlong#3]
Hi,

Having installed Filtlong successfully today I'm testing it on a set of reads from a barcoded MinION run - I used Porechop to demultiplex and then used cat to merge two barcode bins together (they were from the same strain).  

I used this command to run Filtlong:
`filtlong --min_length 5000 --target_bases 160000000 <in_file.fastq> | gzip > <out_file.fastq.gz`

This ran to completion, but the output fastq.gz seems a bit mangled. I've tried several different conversions from fastq to fasta (I'm using ABruijn to assemble so need fasta) but they all get confused and fail - fastq_to_fasta from fastx-toolkit says "Segmentation fault (core dumped)", for example. 

I think perhaps there's something about my input file which is throwing off Filtlong's filtering, but I haven't had this problem with it before (fastq_to_fasta on the original fastq works fine) so don't know how to fix it myself! I've attached the raw fastq and the Filtlonged fastq on my Google Drive, in case that helps figure out what's happening: https://drive.google.com/drive/folders/0B7A9vAPzC1yCbTVZek9WNDJULVU?usp=sharing

Sorry to be a pain!
Nat

**Comment by rrwick** [comment]
Hi Nat,

I downloaded your files but I can't spot anything obviously wrong with them. When I try this command:
`gunzip -c BP_UK36_raw.fastq.gz | fastq_to_fasta > BP_UK36_raw.fasta`
I get an error: `Error: invalid quality score data on line 1148 (quality_tok = "+"`
But I think this is a problem with fastq_to_fasta, not the file (https://www.biostars.org/p/233759/).

When I use a different tool, it works fine, both for the raw and Filtlong files:
`seqtk seq -A BP_UK36_raw.fastq.gz > BP_UK36_raw.fasta`
`seqtk seq -A BP_UK36_filtlong40.fastq.gz > BP_UK36_filtlong40.fasta`

Maybe I'm overlooking something, but I can't spot anything obviously wrong:
```
gunzip -c BP_UK36_filtlong40.fastq.gz | paste - - - - | cut -f 1 | cut -c-1 | sort | uniq  # the first line of each group of 4 always starts with @
gunzip -c BP_UK36_filtlong40.fastq.gz | paste - - - - | cut -f 2 | cut -c-1 | sort | uniq  # the second line of each group of 4 always starts with a nucleotide
gunzip -c BP_UK36_filtlong40.fastq.gz | paste - - - - | cut -f 3 | sort | uniq  # the third line of each group of 4 is always just +
gunzip -c BP_UK36_filtlong40.fastq.gz | wc -l  # the number of lines in the file is divisible by 4
```

I also tried assembling them with unicycler:
`unicycler -l BP_UK36_filtlong40.fastq.gz -o assembly`
and I got this beautiful circular 4 Mbp contig:
<img width="211" alt="screen shot 2017-08-30 at 2 23 04 pm" src="https://user-images.githubusercontent.com/7053555/29855390-dacc3af0-8d8e-11e7-89f4-a48a32276fb9.png">

So in the end I'm inclined to say that the fastq is fine! Perhaps try seqtk and see if that works for you?

Ryan

**Comment by nataliering** [comment]
How bizarre! Yes, seqtk works for me too, I hadn't tried it before, just fastq_to_fasta and a couple of one-liners I usually use (those were either failing or leaving some of the quality lines in). I'll just use seqtk in future!

Thanks again for you speedy and thorough response, sorry it turned out this wasn't much of a real problem! I used Unicycler for a hybrid assembly overnight, and it's made me a perfect contig - I'll try it on my Filtlonged reads today too!

Nat
