### ISSUE TITLE
Error during scoring long reads

### ISSUE THREAD

**Issue by Tipplynne** [rrwick/Filtlong#30]
Good day and thank you for writing and sharing great softwares.

I am currently trying to run filtlong on ~80Gb of promethion data, on the linux HPC at my university. I installed filtlong as a callable module and it runs well for filtlong -h.

When I try to run it on my file with the following instructions (run within a bash script on the slurm scheduler):
`filtlong --min_length 500 --keep_percent 60 --target_bases 50000000000 20190209_Cavi_pass.fastq | gzip > Cavi_prom_filtlong-best60reads.fastq
`

I get this error:
`Scoring long reads
^M  terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid`

Is this an installation issue? Any advice would be great!
Thanks and kind regards
Crystal

**Comment by KasperSkytte** [comment]
I get the exact same error when running through a singularity container based on ubuntu18. Fixed by setting locales correctly, specifically the `LC_ALL`.

**Comment by KasperSkytte** [comment]
In reality added the following to my definition file:

```
apt install locales -y
  # Configure default locale
  echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
  locale-gen en_US.utf8
  /usr/sbin/update-locale LANG=en_US.UTF-8
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
```

**Comment by Tipplynne** [comment]
Thanks for the advice, I didn't have permission to edit locale.gen, but just adding  
` export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8`
to my ~/.bashrc seems to have fixed the problem!
