### ISSUE TITLE
Question: Will Filtlong remove invalid/bad reads from ONT FASTQ data?

### ISSUE THREAD

**Issue by cement-head** [rrwick/Filtlong#31]
Will filtlong remove invalid reads (e.g. mismatched sequence & quality score length) reads?

**Comment by rrwick** [comment]
No - sorry! If mismatches sequence/quality lengths are encountered, Filtlong will quit with an `incorrect FASTQ format` error message. If you've ended up with mangled FASTQ files that look like this, you'll need to clean them up prior to Filtlong.
