### ISSUE TITLE
Phred to basecalling probability conversion table?

### ISSUE THREAD

**Issue by GeoMicroSoares** [rrwick/Filtlong#4]
Hey @rrwick , trying to now use Filtlong to filter my .fastq instead of fastq_to_fast5.
Was using Phred = 9 as a value to quality-filter my .fastq; how do I now convert this to a probability in order to apply --min_mean_q ?

Also, quick Q: how about if I'm not using zipped files? Can I just go ```filtlong --min_mean_q XX input.fastq > output.fastq?```

Thanks!

**Comment by rrwick** [comment]
Hi André,

To convert a Phred score to the probability of an error, use 10^(-Q/10). So to convert it to the probability of being correct (as Filtlong expects), it's 1 - 10^(-Q/10). For for your example, it's 1 - 10^-0.9 = 0.874 = 87.4%. For Filtlong, this is `--min_mean_q 87.4`. I should probably add a new option, something like `--min_mean_phred` where you can give it a Phred score and it will do this calculation internally. I'll add that to my 'future features' list. Thanks!

And regarding your second question: yes, you can certainly skip the gzipping step. Filtlong outputs in fastq format, so your command would work just fine.

Ryan
