### ISSUE TITLE
Documentation "--min_mean_q" should be a % accuracy

### ISSUE THREAD

**Issue by Kirk3gaard** [rrwick/Filtlong#7]
Hi Ryan

Thanks for yet another great tool.

Any chance that you would specify in the documentation that the "--min_mean_q" should be a % accuracy and not a phred score?

Best regards Rasmus

**Comment by rrwick** [comment]
Okay, I've added a blurb in the [Method section](https://github.com/rrwick/Filtlong#method). Sorry for any confused caused!

Ryan
