### ISSUE TITLE
Newer version of filtlong interprets input as fasta even though it is fastq

### ISSUE THREAD

**Issue by lfaller** [rrwick/Filtlong#8]
Hello all,

I recently set up a barebones ubuntu box through docker and wanted to install flitlong into it as follows:

```
git clone https://github.com/rrwick/Filtlong.git && cd Filtlong && make -j
```

When I tried filtering minion data, I ran into the following error:

```
$> filtlong --version
Filtlong v0.2.0

$> filtlong --min_length 1000 --keep_percent 90 --target_bases 500000000 input.fastq > filtered.fastq && touch filtered.ok

Scoring long reads
  78053 reads (246851956 bp)Error: FASTA input not supported without an external reference
```

I verified that the input is indeed a *fastq* file, not fasta, and it seems to be filtered fine on another machine, which happens to have an older version of filtlong installed:

```
$> filtlong --version
Filtlong v0.1.1

$> filtlong --min_length 1000 --keep_percent 90 --target_bases 500000000 input.fastq > filtered.fastq && touch filtered.ok

Scoring long reads
  110,121 reads (344,972,626 bp)

Filtering long reads
  target: 310,475,363 bp
  keeping 310,475,879 bp

Outputting passed long reads
```

I put the input file on dropbox here: https://www.dropbox.com/s/b94bk7s14xv7kum/input.fastq?dl=0

Should I downgrade to an earlier version of Filtlong? Any suggestions are appreciated!

**Comment by rrwick** [comment]
Uh oh - that's not good! Yes, for the time being, I'd say just go back to the previous Filtlong version.

Thanks so much for providing the input - that's super helpful for debugging the problem. I've downloaded it so you can remove it from Dropbox now to free up some space.

I'll let you know when I've figured it out!

Ryan

**Comment by rrwick** [comment]
Okay, I've spotted the problem in the middle of the FASTQ:
```
@39192ae4-b5d4-454b-b27a-54e6d0aa182c runid=07daa75f0647a6409d8330252a91bf61f951066c sampleid=12-13-17_sample1 read=896 ch=124 start_time=2017-12-13T23:12:15Z
ATCGCGCAGGTAATACTTCGTTCAGTTACAATATTCAGTCGAAAACCGGGTGGCGAAACAGGCCAGCCCCGTCACCGGCACTGACCATTACAGATCACGCATATACTACCACGCTGTATCAACAAAACAAACCTGATTTTCTCTGAATAATTATTCATG...
+
""&$%#$#%&&(&'#)$&')+++&*,0()&$%$$$#(+32&+-(%)'$,*''&''-0*+(&%&%$%'*(&#%%#%&($'$&#%%''&)'&))+%,)%%#%#$$&%(''*+%,&()()*,)(&',22.'*+'()&%(*11.*1023,440./-&*0+(*'...
@b89bd602-42d8-4115-943d-b16e72e0ebbd runid=07daa75f0647a6409d8330252a91bf61f951066c sampleid=12-13-17_sample1 read=1053 ch=125 start_time=2017-12-13T23:12:13Z
TTGCTCGGTAGCCGTTCAGTTACGTATTGCTTCTGTTCAGGTGGCCAAATTCACTATGCCACTACAAAATAAAATATTATGCTAAAAACACTTGATAAGATCTTTACAAAGTCATAATTGAATTTAGTTTATTAAGGCAATAGAAACCCCATCAACATG...
@2ece7318-e288-4dbb-9fc4-99e49fc83b29 runid=355484ce20306d409f4bb1efb00441565104b999 sampleid=12-13-17_sample1 read=126 ch=226 start_time=2017-12-13T22:17:20Z
TTGCATCGGTATGCGCTTCACGTTCCAGTTACGTATTGCTCGCCAGCGTCGATAACGCAGGTATTGCCTTACTGGACGCGGCACATCTTTCGCAGCACCCTGAACTATCAACTGCACTGCGTATTACGTGAGGAAAGCGGCTCAGGGCAAACAGGAAAC...
+
#''&$&,)+-**('&'+)*&()/0)(%*1/-.18,7,++86((*()*,//--/)*)%('/-+)+)'*'()$*('+))3,''&%'(*1++*('*'')'-,)*1,5././/*%+&%&&)**.*-)'*(+,/*).().-&)09233283234:;/*)%&&$$...
```

Read `b89bd602-42d8-4115-943d-b16e72e0ebbd` is missing the `+` line and the quality line, so Filtlong was interpreting that read (and only that one) as a FASTA record.

In a sense, Filtlong was doing the right thing, but its error message wasn't very informative. I've made a change so the error message now looks like this:
```
Scoring long reads
  78,053 reads (246,851,956 bp)

Error: could not parse input reads
  problem occurred at read b89bd602-42d8-4115-943d-b16e72e0ebbd
```

I've pushed the changes up to GitHub, so if you clone and install again it should work better! The solution for your read set would be to repair that odd read. Maybe something when wrong in an earlier stage of processing?

Ryan

**Comment by lfaller** [comment]
Something in the fastq file must have gotten scrambled upstream :-( thank you for adding this informative error message!
